### ISSUE TITLE
jade protect filter broken?

### ISSUE THREAD

**Issue by caseywstark** [fivesixty/notepages#19]
I got everything up and running, but going to a notepages page throws a SyntaxError. That is, the front page renders fine, but going to any other url, I get:

500 SyntaxError: Unexpected token ILLEGAL
at Object.Function (unknown source)
at Object.compile (/home/caseywstark/notepages/node_modules/jade/lib/jade.js:160:8)
at Function.compile (/home/caseywstark/notepages/node_modules/express/lib/view.js:68:33)
at ServerResponse._render (/home/caseywstark/notepages/node_modules/express/lib/view.js:417:18)
at ServerResponse.render (/home/caseywstark/notepages/node_modules/express/lib/view.js:318:17)
at Promise. (/home/caseywstark/notepages/notepages/server.js:149:11)
at Promise. (/home/caseywstark/notepages/node_modules/mongoose/lib/promise.js:120:8)
at Promise. (events.js:67:17)
at Promise.emit (/home/caseywstark/notepages/node_modules/mongoose/lib/promise.js:59:38)
at Promise.complete (/home/caseywstark/notepages/node_modules/mongoose/lib/promise.js:70:20)

I searched around and it sounded like a Jade syntax error. I tried debugging with the jade bin and it was fine after I took out the MathJax script include and all references to the page var. I tried adding each piece in one at a time -- the references to page work fine and the page renders, but as soon as I include the MathJax block, I get the same error.

I'm sorry I don't have a fix to this, but I've never worked with node, express, or jade.

**Comment by caseywstark** [comment]
I got it working with the Jade pipe syntax to include raw HTML, but this is more of a quick fix.
